feat: make port optional in discovery node
colyseus/colyseus pull request #560
Opened 2023-04-10 19:57 UTC by Wenish

Sometimes you dont want to specify a port so https and wss use the default port.

in cloud env the container in which the server runs may uses internally a other port then under which the server is externally avaiable.
common is internally 8080 and externally 443/80

so this change would allow to set the SELF_PORT env variable to an empty string "" and it would not override it with node.port
only if SELF_PORT is undefined or null

2023-04-10 20:06 UTC, endel requested changes
Thanks for the PR @Wenish, it's a good addition - I'd suggest to avoid using `!!port` though, as it may be confusing to read. (I personally struggle with double negatives even on spoken language 😅 )

2023-04-10 20:06 UTC, endel commented on packages/core/src/discovery/index.ts
> +  return !!port ? `${node.processId}/${host}:${port}` : `${node.processId}/${host}`;
To make it easier to read, I'd suggest writing this way:

```typescript
  const port = process.env.SELF_PORT ?? node.port;
  return (port !== undefined) 
    ? `${node.processId}/${host}:${port}` 
    : `${node.processId}/${host}`;
```

2023-04-11 16:52 UTC, Wenish commented
@endel what you think about how it is now?

2023-04-12 00:00 UTC, Wenish commented
done

2023-04-12 02:44 UTC, merged